"""Minimal evaluator agent."""

from __future__ import annotations

from llm import load_llm_config
from runtime.artifact_context import (
    add_to_session_working_set,
    preserve_from_task_working_set,
    register_task_artifact,
)
from runtime.instruction_resolver import resolve_active_instruction_artifact
from runtime.scheduler import select_next_runnable_task
from runtime.state import RuntimeState
from runtime.tool_runner import ToolRunner
from schema import (
    ArtifactKind,
    Decision,
    DecisionRoute,
    ExecutionOutcome,
    EvaluateArgs,
    ReplanMode,
    ReplanRequest,
    SessionPhase,
    TaskRetryAdvice,
    TaskStatus,
    ToolName,
)
from tools.registry import ToolRegistry, build_default_tool_registry


class EvaluatorAgent:
    """Evaluates successful task outputs and routes the next step."""

    def __init__(self, registry: ToolRegistry | None = None) -> None:
        self._registry = registry or build_default_tool_registry()
        self._tool_runner = ToolRunner(self._registry)

    def run(self, state: RuntimeState) -> RuntimeState:
        session = state["session"]
        current_task_id = session.current_task_id
        if current_task_id is None:
            raise ValueError("current_task_id is required during evaluate")

        task = state["tasks"][current_task_id]
        task_state = session.task_states[current_task_id]
        if task_state.latest_execute_checkpoint != "passed" or not task_state.latest_artifact_ids:
            raise ValueError("EvaluatorAgent only accepts successful execute checkpoint outputs")
        if not self._is_evaluable_candidate_ref(state, task_state.latest_artifact_ids[-1]):
            decision = self._build_invalid_candidate_replan_decision(
                state=state,
                task_id=current_task_id,
                candidate_ref=task_state.latest_artifact_ids[-1],
            )
            task_state.latest_evaluate_checkpoint = "failed"
            self._clear_task_retry_context(task_state)
            task_state.status = TaskStatus.REPLANNED
            session.current_task_id = None
            session.phase = SessionPhase.PLANNING
            session.latest_decision_id = decision.id
            state["decision"] = decision
            state["session"] = session
            return state

        task_state.evaluator_checkpoint_count += 1
        latest_edit_instruction = self._find_latest_edit_instruction(state, current_task_id)
        evaluate_execution = self._tool_runner.run(
            state,
            ToolName.EVALUATE,
            task_id=current_task_id,
            loop_index=task_state.loop_count,
            args=EvaluateArgs(
                input_refs=self._build_evaluate_input_refs(state, current_task_id),
                candidate_ref=task_state.latest_artifact_ids[-1],
                candidate_refs=list(task_state.latest_artifact_ids),
                instruction=latest_edit_instruction or task.instruction,
                checks=task.acceptance_criteria,
            ),
        )
        state["operations"].append(evaluate_execution.invocation)
        if evaluate_execution.invocation.status == "failed":
            decision = self._build_evaluate_failure_replan_decision(
                state=state,
                task_id=current_task_id,
                error=evaluate_execution.invocation.error or {},
            )
            task_state.latest_evaluate_checkpoint = "failed"
            self._clear_task_retry_context(task_state)
            task_state.status = TaskStatus.REPLANNED
            session.current_task_id = None
            session.phase = SessionPhase.PLANNING
            session.latest_decision_id = decision.id
            state["decision"] = decision
            state["session"] = session
            return state
        for artifact in evaluate_execution.artifacts:
            register_task_artifact(
                state,
                current_task_id,
                artifact,
                usage="latest evaluation feedback",
                selection_reason="generated by the evaluator for the current task checkpoint",
            )

        evaluation_payload = evaluate_execution.artifacts[0].payload if evaluate_execution.artifacts else {}
        route = self._route_from_evaluation_payload(
            evaluation_payload=evaluation_payload,
            state=state,
            task_id=current_task_id,
        )

        common = {
            "id": f"dec_eval_{current_task_id}_{task_state.evaluator_checkpoint_count:03d}",
            "route": route,
            "task_id": current_task_id,
            "plan_id": session.current_plan_id,
            "source_execution_outcome": task_state.latest_execution_outcome,
            "candidate_artifact_ids": list(task_state.latest_artifact_ids),
            "summary": evaluation_payload.get("reason", "structured evaluator checkpoint decision"),
            "issues": self._build_decision_issues(evaluation_payload),
            "meta": {"evaluation_ref": evaluate_execution.artifacts[0].id if evaluate_execution.artifacts else None},
        }

        if route == DecisionRoute.CONTINUE_EXECUTE:
            task_state.latest_evaluate_checkpoint = "failed"
            reason = evaluation_payload.get(
                "reason",
                "continue the current task using evaluator feedback to choose the next tool",
            )
            task_retry = TaskRetryAdvice(
                reason=reason,
                base_candidate_artifact_id=task_state.latest_artifact_ids[-1],
                reuse_artifact_ids=self._build_reuse_artifact_ids(task_state),
                fix_focuses=[reason],
                avoid_changes=["do not discard the original input images"],
            )
            decision = Decision(
                **common,
                task_retry=task_retry,
            )
            self._apply_task_retry_context(state, current_task_id, task_retry)
            task_state.status = TaskStatus.RUNNING
            session.phase = SessionPhase.EXECUTING
        elif route == DecisionRoute.REPLAN:
            task_state.latest_evaluate_checkpoint = "failed"
            self._clear_task_retry_context(task_state)
            decision = Decision(
                **common,
                replan=ReplanRequest(
                    mode=self._fallback_replan_mode(task.type),
                    reason=evaluation_payload.get(
                        "reason",
                        "the current task should not continue as-is after evaluator review",
                    ),
                    preserve_artifact_ids=preserve_from_task_working_set(state, current_task_id),
                ),
            )
            task_state.status = TaskStatus.REPLANNED
            session.current_task_id = None
            session.phase = SessionPhase.PLANNING
        elif route == DecisionRoute.FAIL:
            task_state.latest_evaluate_checkpoint = "failed"
            self._clear_task_retry_context(task_state)
            decision = Decision(**common)
            task_state.status = TaskStatus.FAILED
            session.current_task_id = None
            session.phase = SessionPhase.FAILED
        else:
            task_state.latest_evaluate_checkpoint = "passed"
            self._clear_task_retry_context(task_state)
            decision = Decision(**common)
            task_state.status = TaskStatus.PASSED
            if task_state.latest_artifact_ids:
                task_state.final_artifact_id = task_state.latest_artifact_ids[-1]
                if task_state.final_artifact_id not in state["session"].artifact_index.by_type.setdefault(ArtifactKind.IMAGE, []):
                    state["session"].artifact_index.by_type[ArtifactKind.IMAGE].append(task_state.final_artifact_id)
                add_to_session_working_set(
                    state,
                    task_state.final_artifact_id,
                    usage="passed task output image",
                    selection_reason="promoted because the task passed and produced a reusable image output",
                )
            for entry in task_state.task_working_set:
                artifact = state["artifacts"].get(entry.artifact_id)
                if artifact is None or artifact.kind != ArtifactKind.INSTRUCTION:
                    continue
                add_to_session_working_set(
                    state,
                    artifact.id,
                    usage="passed task instruction context",
                    selection_reason="promoted because it may help initialize later tasks",
                )
            next_task_id = select_next_runnable_task(state)
            if next_task_id is None:
                session.final_result_id = task_state.final_artifact_id
                session.current_task_id = None
                session.phase = SessionPhase.DONE
            else:
                session.current_task_id = next_task_id
                session.task_states[next_task_id].status = TaskStatus.RUNNING
                session.phase = SessionPhase.EXECUTING

        session.latest_decision_id = decision.id
        state["decision"] = decision
        state["session"] = session
        return state

    def _build_decision_issues(self, evaluation_payload: dict) -> list[str]:
        verdict = evaluation_payload.get("verdict")
        reason = str(evaluation_payload.get("reason", "")).strip()
        if verdict in {"pass_with_issues", "needs_revision", "replan"} and reason:
            return [reason]
        return []

    def _build_evaluate_failure_replan_decision(
        self,
        *,
        state: RuntimeState,
        task_id: str,
        error: dict,
    ) -> Decision:
        task = state["tasks"][task_id]
        task_state = state["session"].task_states[task_id]
        error_type = str(error.get("type", "unknown"))
        error_message = str(error.get("message", "evaluate tool failed"))
        return Decision(
            id=f"dec_eval_fail_{task_id}_{task_state.evaluator_checkpoint_count:03d}",
            route=DecisionRoute.REPLAN,
            task_id=task_id,
            plan_id=state["session"].current_plan_id,
            source_execution_outcome=task_state.latest_execution_outcome or ExecutionOutcome.FAILURE,
            candidate_artifact_ids=list(task_state.latest_artifact_ids),
            summary=f"evaluate tool failed: {error_message}",
            issues=[
                "evaluate_tool_failed",
                f"error_type={error_type}",
            ],
            replan=ReplanRequest(
                mode=self._fallback_replan_mode(task.type),
                reason=f"evaluate tool failed before producing usable feedback: {error_message}",
                preserve_artifact_ids=preserve_from_task_working_set(state, task_id),
            ),
        )

    def _is_evaluable_candidate_ref(self, state: RuntimeState, artifact_id: str) -> bool:
        artifact = state["artifacts"].get(artifact_id)
        if artifact is None or artifact.kind != ArtifactKind.IMAGE:
            return False
        return artifact.created_by == ToolName.EDIT.value or artifact.role == "candidate_image"

    def _build_invalid_candidate_replan_decision(
        self,
        *,
        state: RuntimeState,
        task_id: str,
        candidate_ref: str,
    ) -> Decision:
        task = state["tasks"][task_id]
        task_state = state["session"].task_states[task_id]
        artifact = state["artifacts"].get(candidate_ref)
        artifact_kind = getattr(getattr(artifact, "kind", None), "value", getattr(artifact, "kind", None))
        return Decision(
            id=f"dec_eval_invalid_candidate_{task_id}_{task_state.evaluator_checkpoint_count + 1:03d}",
            route=DecisionRoute.REPLAN,
            task_id=task_id,
            plan_id=state["session"].current_plan_id,
            source_execution_outcome=task_state.latest_execution_outcome or ExecutionOutcome.FAILURE,
            candidate_artifact_ids=list(task_state.latest_artifact_ids),
            summary=f"evaluator expected an edit candidate image but received {candidate_ref}",
            issues=[
                "invalid_evaluation_candidate",
                f"candidate_ref={candidate_ref}",
                f"candidate_kind={artifact_kind or 'unknown'}",
            ],
            replan=ReplanRequest(
                mode=self._fallback_replan_mode(task.type),
                reason="execute checkpoint ended without an evaluable edit candidate image",
                preserve_artifact_ids=preserve_from_task_working_set(state, task_id),
            ),
        )

    def _apply_task_retry_context(
        self,
        state: RuntimeState,
        task_id: str,
        task_retry: TaskRetryAdvice,
    ) -> None:
        task_state = state["session"].task_states[task_id]
        retry_ids: list[str] = []

        for artifact_id in state["session"].artifact_index.by_type.get(ArtifactKind.IMAGE, []):
            if artifact_id.startswith("art_img_input_") and artifact_id not in retry_ids:
                retry_ids.append(artifact_id)

        if task_retry.base_candidate_artifact_id and task_retry.base_candidate_artifact_id in state["artifacts"]:
            retry_ids.append(task_retry.base_candidate_artifact_id)

        latest_instruction_id = self._find_latest_instruction_artifact_id(state, task_id)
        if latest_instruction_id:
            retry_ids.append(latest_instruction_id)

        for artifact_id in task_retry.reuse_artifact_ids:
            if artifact_id in state["artifacts"] and artifact_id not in retry_ids:
                retry_ids.append(artifact_id)

        task_state.retry_input_artifact_ids = retry_ids
        task_state.retry_context_text = self._build_retry_context_text(task_retry)
        task_state.task_working_set = []
        task_state.resolved_input_artifact_ids = []
        task_state.input_selection_reasoning = None
        task_state.input_validation_summary = None

    def _clear_task_retry_context(self, task_state) -> None:
        task_state.retry_input_artifact_ids = []
        task_state.retry_context_text = None

    def _find_latest_instruction_artifact_id(
        self,
        state: RuntimeState,
        task_id: str,
    ) -> str | None:
        artifact = resolve_active_instruction_artifact(state, task_id)
        return artifact.id if artifact is not None else None

    def _build_retry_context_text(self, task_retry: TaskRetryAdvice) -> str:
        lines = [
            "Evaluator feedback:",
            "- Continue the current task; choose the next tool based on this feedback.",
            f"- Reason: {task_retry.reason}",
        ]
        if task_retry.base_candidate_artifact_id:
            lines.append(f"- Base candidate: {task_retry.base_candidate_artifact_id}")
        if task_retry.reuse_artifact_ids:
            lines.append(f"- Reuse artifacts: {', '.join(task_retry.reuse_artifact_ids)}")
        if task_retry.fix_focuses:
            lines.append("- Fix focuses:")
            for index, item in enumerate(task_retry.fix_focuses, start=1):
                lines.append(f"  {index}. {item}")
        if task_retry.avoid_changes:
            lines.append("- Avoid changes:")
            for index, item in enumerate(task_retry.avoid_changes, start=1):
                lines.append(f"  {index}. {item}")
        return "\n".join(lines)

    def _build_reuse_artifact_ids(self, task_state) -> list[str]:
        return [
            artifact_id
            for artifact_id in task_state.task_artifact_ids[-8:]
            if artifact_id != task_state.latest_artifact_ids[-1]
        ]

    def _route_from_evaluation_payload(
        self,
        *,
        evaluation_payload: dict,
        state: RuntimeState,
        task_id: str,
    ) -> DecisionRoute:
        verdict = evaluation_payload.get("verdict")
        if verdict in {"pass", "pass_with_issues"}:
            return DecisionRoute.PASS
        if verdict == "needs_revision":
            return DecisionRoute.CONTINUE_EXECUTE
        if verdict == "replan":
            return DecisionRoute.REPLAN
        return self._fallback_route(state, task_id)

    def _fallback_route(self, state: RuntimeState, task_id: str) -> DecisionRoute:
        max_evaluator_checkpoints = state.get("max_evaluator_checkpoints", 3)
        task_state = state["session"].task_states[task_id]
        desired_route = DecisionRoute(state["input"].get("desired_decision_route", "replan"))
        if desired_route == DecisionRoute.CONTINUE_EXECUTE and task_state.evaluator_checkpoint_count >= max_evaluator_checkpoints:
            return DecisionRoute.REPLAN
        return desired_route

    def _fallback_replan_mode(self, task_type: str) -> ReplanMode:
        if task_type in {"local_edit", "compose_subject", "reference_edit"}:
            return ReplanMode.SPLIT_TASK
        return ReplanMode.REROUTE_PLAN

    def _use_llm(self, state: RuntimeState) -> bool:
        if not state["input"].get("use_llm", False):
            return False
        try:
            config = load_llm_config()
        except Exception:
            return False
        return bool(config.api_key and config.base_url and config.model_name)

    def _build_evaluate_input_refs(self, state: RuntimeState, task_id: str) -> list[str]:
        task_state = state["session"].task_states[task_id]
        refs = (
            task_state.resolved_input_artifact_ids
            or [entry.artifact_id for entry in task_state.task_working_set]
            or state["tasks"][task_id].input_artifact_ids
        )
        return [
            artifact_id
            for artifact_id in refs
            if artifact_id in state["artifacts"]
            and state["artifacts"][artifact_id].kind == ArtifactKind.IMAGE
        ]

    def _find_latest_edit_instruction(self, state: RuntimeState, task_id: str) -> str | None:
        for operation in reversed(state.get("operations", [])):
            if operation.task_id != task_id or operation.tool_name != ToolName.EDIT:
                continue
            instruction = operation.args.get("instruction")
            if isinstance(instruction, str) and instruction.strip():
                return instruction.strip()
        return None
